FROM nginx:alpine

# Создаём непривилегированного пользователя
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY ./index.html /usr/share/nginx/html/index.html
COPY ./nginx.nonroot.conf /etc/nginx/nginx.conf

# Непривилегированный пользователь должен иметь доступ только к контенту.
RUN chown -R appuser:appgroup /usr/share/nginx/html

# Переключаемся на пользователя
USER appuser

EXPOSE 8080

ENTRYPOINT ["nginx", "-g", "daemon off;"]
