services:
  web:
    image: my-nginx-practice:v1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-nginx-web
    ports:
      - "8081:80"
    depends_on:
      - db
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /tmp
    volumes:
      - ./nginx_logs:/var/log/nginx
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - backend

  db:
    image: postgres:15-alpine
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
